import io.netty.buffer.UnpooledByteBufAllocator.InstrumentedUnpooledUnsafeNoCleanerDirectByteBuf;
public class FunctionUse22054 {
public void funcUse() {
InstrumentedUnpooledUnsafeNoCleanerDirectByteBuf instrumentedunpooledunsafenocleanerdirectbytebuf = new InstrumentedUnpooledUnsafeNoCleanerDirectByteBuf();
instrumentedunpooledunsafenocleanerdirectbytebuf.reallocateDirect(null,null);
}
}